version: "3.8"

services:
  payments-service:
    image: payments-service:latest
    container_name: payment-service
    build: .
    ports:
      - "8083:8083"
    env_file:
      - .env.docker
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_TOOL_OPTIONS: >
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=60
        -XX:InitialRAMPercentage=10
        -XX:ActiveProcessorCount=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - payments-net
      - events-backend

  postgres:
    image: postgres:15-alpine
    container_name: postgres-payments
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payments-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments_user -d payments_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - payments-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  payments-net:
    external: true

  events-backend:
    external: true