spring:
  flyway:
    enabled: true
    schemas: payment
    baseline-on-migrate: true

  config:
    activate:
      on-profile: hml

  datasource:
    url: ${DB_POSTGRES_URL}
    username: ${DB_POSTGRES_USER}
    password: ${DB_POSTGRES_PASSWORD}

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

stripe:
  secretKey: ${SECRET_KEY_STRIPE}
  publicKey: ${PUBLIC_KEY_STRIPE}

server:
  port: 8083

app:
  rabbit:
    listener:
      enabled: true