spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${DB_POSTGRES_URL}
    username: ${DB_POSTGRES_USER}
    password: ${DB_POSTGRES_PASSWORD}

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: redis
      port: 6379

management:
  metrics:
    export:
      otlp:
        enabled: true
        url: http://otel-collector:4318/v1/metrics
        protocol: http/protobuf

stripe:
  secretKey: ${SECRET_KEY_STRIPE}
  publicKey: ${PUBLIC_KEY_STRIPE}

server:
  port: 8083
