apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
      custom:
        - seriesQuery: 'process_cpu_usage{job="api-payments-hml"}'
          resources:
            overrides:
              namespace:
                resource: namespace
              pod:
                resource: pod
          name:
            as: "api_cpu"
          metricsQuery: 'avg(rate(process_cpu_usage{job="api-payments-hml"}[1m])) by (pod) * 100'
